export const MedicalSupplies = [
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04020055",
    ProductDescription: "CANNULA, O2, NASAL, ADULT",
    Category: "MEDICAL",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04030173",
    ProductDescription: "CATHETER, UMBILICAL, PUR 2.5FR, VYGON, 1270-02",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04150323",
    ProductDescription: "CERVICAL COLLAR, RIGID, ADULT, TYNOR",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04370123",
    ProductDescription:
      "TRACHEOSTOMY TUBE, NEONATAL, CUFFED, STERILE, SIZE 5.5MM (ID), TRACOE",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04370169",
    ProductDescription: "TUBE, ENDOTRACHEAL, CUFFED, SIZE 7.5",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04580059",
    ProductDescription: "SPHINCTEROTOMES , PRELOADED WITH VISIGLIDE, OLYMPUS",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04670007",
    ProductDescription: "ZERO TIP AIRWAY RETRIEVAL BASKET",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC05080534",
    ProductDescription: "CHEST BINDER W/STERNAL PAD XXL DYNAMIC 1435-006",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04020042",
    ProductDescription: "NASAL CANULA,O2STAR CURVED SIZE L GREETMED",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04150413",
    ProductDescription: "EARING, EARSTD, 7582-6015-23, OCT ROSE AB CRY",
    Category: "MEDICAL CONSUMABLES",
    UOM: "PAIR",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04650032",
    ProductDescription: "EYE PACK,ENAYAH,CPT-02761-001",
    Category: "MEDICAL",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04080079",
    ProductDescription:
      "Sealer, Tissue, XL Large Jaw, Enseal, 38mm, ETHICON JNJ",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04090009",
    ProductDescription:
      "Tape, Splint, Plain, Cellacast, 15cmx4.5m, OPTIMA, OSF600",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04150196",
    ProductDescription: "ENDOGIA, ULTRA UNIV SHT, STAPLER, COVIDIEN",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04220007",
    ProductDescription: "Container, Sharp, 6.5ltr",
    Category: "MEDICAL",
    UOM: "EACH",
  },
  {
    Store: 75,
    StoreName: "WH. Main medical supplies store",
    ProductCode: "MC04220025",
    ProductDescription:
      "SERIGRAPHIED POLYPROPYLENE CONT 5L,WHITE PRESS CLOSE LID,3L",
    Category: "MEDICAL CONSUMABLES",
    UOM: "EACH",
  },
];
